# Generated by Django 6.0.6 on 2026-07-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='logo',
            field=models.ImageField(blank=True, upload_to='providers/logos/'),
        ),
    ]
