# Generated by Django 6.0.6 on 2026-07-06 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pressing', 'Pressing…'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_main', models.BooleanField(default=False, help_text='Display this playlist on the front page')),
                ('mp4_file', models.FileField(blank=True, upload_to='playlists/mp4/')),
                ('hls_manifest', models.FileField(blank=True, upload_to='playlists/hls/')),
                ('poster', models.ImageField(blank=True, upload_to='playlists/posters/')),
                ('press_task_id', models.CharField(blank=True, max_length=64)),
                ('press_error', models.TextField(blank=True)),
                ('pressed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('duration_override', models.PositiveIntegerField(blank=True, null=True)),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='playlist_items', to='content.mediaitem')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='playlists.playlist')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('playlist', 'media_item')},
            },
        ),
    ]
