# Generated by Django 6.1.1 on 2026-09-24 11:34

import playlists.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='mp4_file',
            field=models.FileField(blank=True, storage=playlists.storages.attachment_storage, upload_to='playlists/mp4/'),
        ),
    ]
