#!/usr/bin/env bash
set -euo pipefail

az acr login --name ${AZURE_REGISTRY_NAME}

cp envs/.env.example envs/.env

docker compose build web

azure_tag="${AZURE_REGISTRY_NAME}.azurecr.io/ped-tv-web:${GITHUB_SHA}"
docker tag ped-tv-web:latest ${azure_tag}
docker push ${azure_tag}

s/deploy-revision.py \
    --name ${AZURE_LIVE_APP_NAME} \
    --resource-group ${AZURE_RESOURCE_GROUP} \
    --git-hash ${GITHUB_SHA}
