# Generated by Django 6.0.6 on 2026-07-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='video_duration',
            field=models.FloatField(blank=True, help_text='Clip length in seconds (videos only, populated automatically)', null=True),
        ),
    ]
