# Generated by Django 6.0.6 on 2026-07-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='media_type',
            field=models.CharField(choices=[('video', 'Video'), ('image', 'Image')], default='image', max_length=10),
        ),
    ]
