# Generated by Django 6.0.6 on 2026-07-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_mediaitem_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='media_type',
            field=models.CharField(blank=True, choices=[('video', 'Video'), ('image', 'Image')], max_length=10, null=True),
        ),
    ]
